### ISSUE TITLE
[frontend] KFP v1 Pipeline Run Details Page Component Status shows "Execution was skipped" and "ML Metadata not found" 

### ISSUE THREAD

**Issue by ahsan-habib-ta** [kubeflow/pipelines#11457]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?

Kubeflow manifest 1.9.1 (multi-user)
k8s version: 1.29 (AWS EKS)

*  KFP version: 

- kubeflow pipeline 2.3.0
- Argo-workflow: v3.4.17
- KFP Python SDK: 1.8.2 

### Steps to reproduce

- Crerate a KFP v1 Pipeline based on [hello_world](https://github.com/kubeflow/pipelines/blob/sdk/release-1.8/samples/core/helloworld/hello_world.py) example and also disable component caching by setting `max_cache_staleness = "P0D"` . 
- Create a Experiment from UI and create a run for the `hello_world` pipeline.
- Go to the Run Details page and wait for the run to complete and refresh the page.
- Component status  shows "Execution was skipped and outputs were taken from cache" though the component was executed.
- Click on "ML Metadata" tab from component details section and it gives "Corresponding ML Metadata not found." though database inspection shows the metadata exists.  

<img width="1314" alt="v1_run_status_and_metadata" src="https://github.com/user-attachments/assets/3b30111a-1b03-47f1-a9a1-7cd31cd39bac">

### Expected result

Don't expect to see wrong status message "Execution was skipped and outputs were taken from cache" and expect to see Metadata information on the UI.

### Materials and Reference

This issue is related to Argo-workflow version v3.4.17 because from version v3.4.0 ([Changelog](https://github.com/argoproj/argo-workflows/blob/main/CHANGELOG.md#v340-rc1-2022-08-09)) argo-workflow use Pod naming format v2.   

Argo-workflow v2 pod-naming format: `[workflow-name]-[step-template-name]-[random-number-string]` [[Ref](https://github.com/argoproj/argo-workflows/issues/7646)] and it's different from node_id format `[workflow-name]-[random-number-string]` 

Because of this formatting change [function](https://github.com/kubeflow/pipelines/blob/2.3.0/frontend/src/lib/StatusUtils.ts#L122-L131) `wasNodeCached` fails to determine cache status [[similar issue](https://github.com/kubeflow/pipelines/issues/4814)]. 

Updating the of the function to the following fixes the cache status issue 

```

function wasNodeCached(node: NodeStatus): boolean {
  const artifacts = node.outputs?.artifacts;
  // HACK: There is a way to detect the skipped pods based on the WorkflowStatus alone.
  // All output artifacts have the pod name (same as node ID) in the URI. But for skipped
  // pods, the pod name does not match the URIs.
  // (And now there are always some output artifacts since we've enabled log archiving).
  const split = node.id.split('-');
  const hash = split[split.length - 1];
  const prefix = split.slice(0, split.length - 1).join('-');
  const pod_name = prefix.concat('-', node.templateName).concat('-',hash);

  return !artifacts || !node.id || node.type !== 'Pod'
    ? false
    : artifacts.some(artifact => artifact.s3 && !artifact.s3.key.includes(node.id));
    : artifacts.some(artifact => artifact.s3 && !(artifact.s3.key.includes(node.id) || artifact.s3.key.includes(pod_name)));
}
```

Because of the same component pod name formatting change UI also fails to [fetch](https://github.com/kubeflow/pipelines/blob/2.3.0/frontend/src/pages/RunDetails.tsx#L272-L274) Metadata formation. 

```
    const selectedExecution = mlmdExecutions?.find(
      execution => ExecutionHelpers.getKfpPod(execution) === selectedNodeId,
    );
```

---

Impacted by this bug? Give it a 👍.

**Comment by ahsan-habib-ta** [comment]
Hi

I would like to work on this issue.
If it's ok, please assign the issue to me!

Regards
Ahsan

**Comment by juliusvonkohout** [comment]
@ahsan-habib-ta can you retry with Kubeflow 1.10.0 / master branch which includes KFP 2.4.1 ?

CC @hbelmiro @HumairAK we are also experiencing this in Kubeflow 1.9.1

**Comment by juliusvonkohout** [comment]
CC @milinddethe15 @akagami-harsh if you are interested

**Comment by milinddethe15** [comment]
> [@ahsan-habib-ta](https://github.com/ahsan-habib-ta) can you retry with Kubeflow 1.10.0 / master branch which includes KFP 2.4.1 ?

I will check for master branch. what if issue is already resolved.

**Comment by juliusvonkohout** [comment]
> > [@ahsan-habib-ta](https://github.com/ahsan-habib-ta) can you retry with Kubeflow 1.10.0 / master branch which includes KFP 2.4.1 ?
> 
> I will check for master branch. what if issue is already resolved.

Yes, please try with Kubeflow 1.10.0

**Comment by rvalkenaers** [comment]
I am running KFP 2.4.1 and am still encountering the "Corresponding ML Metadata not found." issue

**Comment by juliusvonkohout** [comment]
Yes i also have it still with Kubeflow 1.10

**Comment by juliusvonkohout** [comment]
/close
due to inactivity
please /reopen if needed.
