### ISSUE TITLE
Pipeline UI: logs keep force scrolling to bottom even after step has finished

### ISSUE THREAD

**Issue by amygdala** [kubeflow/pipelines#1790]
(using KF 0.6.1, pipeline build commit: 812ca7f)

In the Pipelines UI, the pod logs for a step keep autoscrolling back down to the bottom even after the step has finished and no new output is being generated.

That makes the logs essentially unusable for post-run debugging (since you can never keep earlier output in view long enough to read it properly...).

**Comment by Bobgy** [comment]
This is already solved in https://github.com/kubeflow/pipelines/pull/2370

/close

**Comment by amygdala** [comment]
I'm still seeing this in whatever version of pipelines is included in KF 0.7.1 (and it's still as annoying as it has always been)
