### ISSUE TITLE
Pipeline UI does not display the description in the pipeline metadata

### ISSUE THREAD

**Issue by gaoning777** [kubeflow/pipelines#2379]
When the description is specified in the DSL SDK, the generated argo yaml contains the description. However, it is not displayed in the Pipeline UI.

**Comment by numerology** [comment]
Umm.... I found it here for one of our preload sample. Can you specify which sample are you using?

![Image of screenshot](https://lh3.googleusercontent.com/kuAlscORm2CtRnoQ6U1UA4TLOQmi0dzpZdCTkHouO1L3_8eieoI-3vNFNAfK3txoXPbbUMpIMELdL8Qn0noAFFM4YTNdCSI6DU1KWQl01gxgiioITGiQn63CVjA3vzbE46PP-9op_05pSWuK_Er643NRV7ShDZ0PQUsaTgrppPK1I9QnBOLnyI0TEoEKWStiARsFXHaH-LgKva3RrHE0n_to9sRfU2H86LBFssxVPB8iIDdshsIOc7w_VhxMKBHx7JD8nGpWq8PecA0AlfXBayesyvNknjWs6bh6WHS2Vrkrj35WwL_MKqFCQm1Ls_pjCYYVUkgmtC0dP5zLfJDkKfmNLNGRHDosZpvjZxehVsQRJpH_yWt6NY4hyr3mtId3hVYqwbrV8najJTR55o_MbSLiQOtkgoEIjF47rdrETuN0qOr2cE95gUpcw7DBtVddRcopXwoBh0EHDd--cA1UudLXnMYhk6BX6FfUDkcK1XqZFG1L8eZtUFnQ8H3X2Dw95VRErjZTPd7Xo58MyVp7MAR2wlQw9eS4CNEphsb_fpOd3a84-ODshr_aog9nbdjWlPYcFyPhYytoUyz_D1eewJGHnNnNDiPiTkzru8pJuXfEL7L56-rJ1sDkX_AQXMxklxOszslfxai3eI6VeaaYfrsmvu9VuTN63xzy7ljfH1G7Dn8jG2tDk8jGO92daHbOob6j2MCcBKu5dGGN5kIC_dnnavLENxhd4PgZYCjTzqfNlIJX=w579-h813-no)

**Comment by gaoning777** [comment]
Upload any sample with the metadata configured, the description is not displayed.
I'm not referring to the preloaded ones, but the one authored in DSL and uploaded to the UI.

**Comment by gaoning777** [comment]
tag it as frontend, but the root cause might be the backend.

**Comment by numerology** [comment]
Confirmed. Non-preloaded sample does not have description displayed in either pipeline list page or its preview page.

**Comment by Bobgy** [comment]
@gaoning777 thanks for the catch, I can investigate from frontend side.
/assign @Bobgy

**Comment by Bobgy** [comment]
There is not much I can do on this. Frontend uses ListPipeline api and it doesn't include description field back: https://github.com/kubeflow/pipelines/blob/5f1b41171f934b568869e46c39a7f49ac4d336ad/backend/api/pipeline.proto#L75

I think the problem is in Pipeline upload api, it should parse description and fill it in corresponding field in DB.

**Comment by Bobgy** [comment]
@IronPan and @jessiezcc , as I commented above: https://github.com/kubeflow/pipelines/issues/2379#issuecomment-541520849, the fix should be done in backend.

**Comment by Bobgy** [comment]
Should this be p0? Does any one want to pick this?

**Comment by rmgogogo** [comment]
Hi Jing, would you review this one? It seems not a heavy change.

**Comment by haghabozorgi** [comment]
are there any updates on this issue? We are still seeing this behavior

**Comment by numerology** [comment]
> are there any updates on this issue? We are still seeing this behavior

Hi, may I ask which version of KFP deployment and KFP SDK are you using? Thanks

**Comment by haghabozorgi** [comment]
pip3 freeze output shows 
kfp==0.1.40
kfp-server-api==0.1.40

as far as deployment, we are using 
https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_existing_arrikto.0.7.1.yaml

**Comment by numerology** [comment]
> pip3 freeze output shows
> kfp==0.1.40
> kfp-server-api==0.1.40
> 
> as far as deployment, we are using
> https://raw.githubusercontent.com/kubeflow/manifests/v0.7-branch/kfdef/kfctl_existing_arrikto.0.7.1.yaml

The fix in #2783 is not in Kubeflow 0.7 deployment yet. The fix is included in our latest standalone deployment, though. Please see [this guide](https://www.kubeflow.org/docs/pipelines/installation/standalone-deployment/). You might need to use `export PIPELINE_VERSION=0.1.40`

**Comment by Bobgy** [comment]
Part of this issue is resolved in https://github.com/kubeflow/pipelines/pull/2783, which allows passing description from UI (manually typed description at pipeline upload).

However, we should better also support description in dsl annotation, (automatically parsed by backend at pipeline upload).

**Comment by wayzeng** [comment]
> Part of this issue is resolved in #2783, which allows passing description from UI (manually typed description at pipeline upload).
> 
> However, we should better also support description in dsl annotation, (automatically parsed by backend at pipeline upload).

Hi, Is there any updates on DSL side? We still see this issue in kfp==1.8.22. kfp server 2.0.0. Thanks!
