### ISSUE TITLE
Boolean parameters cannot be passed to components defined with the component.yaml specifications

### ISSUE THREAD

**Issue by Intellicode** [kubeflow/pipelines#5111]
### What steps did you take:

Boolean parameters cannot be passed to components defined with the component.yaml specifications:

Example pipeline:

```python
# test_case.py

from kfp import dsl, components

@dsl.pipeline(name="Pipeline", description="Pipeline")
def pipeline(
   param: bool = False
) -> None:
  some_op = components.load_component_from_text(
      """
        name: Pipeline
        inputs:
        - name: param
          type: Bool
        implementation:
          container:
            image: some/container
            args: [
                /opt/conda/envs/py37/bin/python, script.py,
                --job-name, {inputValue: param},
            ]
      """
  )

  some_op(param)

```

```bash
dsl-compile --py test_case.py --output test_case.yaml
```

### What happened:

The dsl-compile step throws an error:

```
kfp.dsl.types.InconsistentTypeException: Incompatible argument passed to the input "param" of component "Pipeline": Argument type "Boolean" is incompatible with the input type "Bool"
```

### What did you expect to happen:

The pipeline should compile succesfully

### Environment:

KFP version: N/A

KFP SDK version:

```
kfp                          1.4.0
kfp-pipeline-spec            0.1.2
kfp-server-api               1.3.0
```

/kind bug
/area sdk

**Comment by gmjonker** [comment]
I fixed this problem by using type "Boolean" instead of "Bool" in the component definition, although that goes directly against https://www.kubeflow.org/docs/pipelines/reference/component-spec/

**Comment by kylebeni** [comment]
this is still a problem in kfp 1.8.14, and the documentation has still not been updated. Input type "Bool" is conspicuously the only input type that isn't fully spelled out, contrary to "Integer", "String", and "Float".

Pipelines run if input is "Boolean", but fail due to the `Argument type "Boolean" is incompatible with the input type "Bool"` error if input is "Bool", as the docs specify.

Can we at least update the docs please?
