### ISSUE TITLE
[sdk] pipeline parameters, CustomPythonPackageTrainingJobRunOp, NoneType object is not subscriptable

### ISSUE THREAD

**Issue by ckchow** [kubeflow/pipelines#6426]
### Environment

*  KFP version: N/A (vertex AI job)
*  KFP SDK version: 1.7.0
*  All dependencies version:
```
kfp==1.7.0
kfp-pipeline-spec==0.1.9
kfp-server-api==1.6.0

google-cloud-pipeline-components==0.1.5
```

### Steps to reproduce
```
@dsl.pipeline(
    name='name',
    pipeline_root='gs://some-place'
)
def train_pipeline(
    # dataset
    batch_size: int,
    train_start_date: str,
    train_end_date: str,
    val_start_date: str,
    val_end_date: str,
    test_start_date: str,
    test_end_date: str,
    bucket_size_s: int,
    anomaly_window_size_s: int,
    device_column: str,
    # model
    outer_units: int,
    inner_units: int,
    learning_rate: float,
    # trainer
    max_epochs: int,
    # dataset [defaults]
    table: str = 'project.dataset.table',
    shuffle_buffer_size: int = 1_000,
    # misc [defaults]
    project: str = 'project',
    location: str = 'us-central1',
    tensorboard_name: str = 'test_tensorboard',
    container_uri: str = 'us-docker.pkg.dev/vertex-ai/training/pytorch-xla.1-7:latest',
    python_package_gcs_uri: str = 'gs://some-place/package.tar.gz',
    python_module: str = 'blah.models.trainer'
):    
    train_op = gcc.aiplatform.CustomPythonPackageTrainingJobRunOp(
        args=[
            # dataset
            '--batch_size', str(batch_size),
            '--train_start_date', str(train_start_date),
            '--train_end_date', str(train_end_date),
            '--val_start_date', str(val_start_date),
            '--val_end_date', str(val_end_date),
            '--test_start_date', str(test_start_date),
            '--test_end_date', str(test_end_date),
            '--bucket_size_s', str(bucket_size_s),
            '--anomaly_window_size_s', str(anomaly_window_size_s),
            '--device_column', str(device_column),
            '--shuffle_buffer_size', str(shuffle_buffer_size),
            '--table', str(table),
            '--project', str(project),
            # model
            '--outer_units', str(outer_units),
            '--inner_units', str(inner_units),
            '--lr', str(learning_rate),
            # trainer
            '--max_epochs', str(max_epochs),
            # misc
            '--cloud'
        ],
        replica_count=1,
        machine_type='n1-standard-8',
        tensorboard=f'projects/{str(project)}/locations/{str(location)}/tensorboard/{str(tensorboard_name)}',
        display_name='funky',
        python_package_gcs_uri=python_package_gcs_uri,
        python_module=python_module,
        container_uri=container_uri,
        project=project,
        location=location
    )

compiler.Compiler().compile(train_pipeline, package_path='../pipelines/train_pipeline.json',
                           type_check=True)
    

api_client = AIPlatformClient(project_id='funky', region='us-central1')

response = api_client.create_run_from_job_spec(
    '../pipelines/train_pipeline.json',
    parameter_values={
        'batch_size': 32,
        'train_start_date': '2021-05-01 UTC',
        'train_end_date': '2021-05-14 UTC',
        'val_start_date': '2021-05-15 UTC',
        'val_end_date': '2021-05-21 UTC',
        'test_start_date': '2021-05-22 UTC',
        'test_end_date': '2021-05-31 UTC',
        'bucket_size_s': 5,
        'anomaly_window_size_s': 60,
        'device_column': 'device_hardware',
        # model
        'outer_units': 64,
        'inner_units': 32,
        'learning_rate': 0.003,
        # trainer
        'max_epochs': 5,
        # dataset [defaults]
        'table': 'blah.blah.table',
        'shuffle_buffer_size': 1_000,
        # misc [defaults]
        'project': 'cool-project',
        'location': 'us-central1',
        'tensorboard_name': 'test_tensorboard',
    }
)
```

yields:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-128-54de1a48b582> in <module>
      1 # generate json pipeline specification
----> 2 compiler.Compiler().compile(train_pipeline, package_path='../pipelines/train_pipeline.json',
      3                            type_check=True)
      4 
      5 

/opt/conda/lib/python3.8/site-packages/kfp/v2/compiler/compiler.py in compile(self, pipeline_func, package_path, pipeline_name, pipeline_parameters, type_check)
   1135       kfp.TYPE_CHECK = type_check
   1136       kfp.COMPILING_FOR_V2 = True
-> 1137       pipeline_job = self._create_pipeline_v2(
   1138           pipeline_func=pipeline_func,
   1139           pipeline_name=pipeline_name,

/opt/conda/lib/python3.8/site-packages/kfp/v2/compiler/compiler.py in _create_pipeline_v2(self, pipeline_func, pipeline_name, pipeline_parameters_override)
   1071 
   1072     with dsl.Pipeline(pipeline_name) as dsl_pipeline:
-> 1073       pipeline_func(*args_list)
   1074 
   1075     self._validate_exit_handler(dsl_pipeline)
<ipython-input-127-62de707bdaca> in train_pipeline(batch_size, train_start_date, train_end_date, val_start_date, val_end_date, test_start_date, test_end_date, bucket_size_s, anomaly_window_size_s, device_column, outer_units, inner_units, learning_rate, max_epochs, table, shuffle_buffer_size, project, location, tensorboard_name, container_uri, python_package_gcs_uri, python_module)
     45     python_module: str = 'blah.models.trainer'
     46 ):    
---> 47     train_op = gcc.aiplatform.CustomPythonPackageTrainingJobRunOp(


/opt/conda/lib/python3.8/site-packages/google_cloud_pipeline_components/aiplatform/utils.py in component_yaml_generator(**kwargs)
    548                           kfp.dsl._pipeline_param.PipelineParam) or serializer:
    549                 if is_mb_sdk_resource_noun_type(param_type):
--> 550                     metadata_type = map_resource_to_metadata_type(param_type)[1]
    551                     component_param_type = metadata_type
    552                 else:

TypeError: 'NoneType' object is not subscriptable
```

I think the aiplatform client / kfp translator function is parsing something wrong. Or perhaps I'm using / not using `str()` enough? It does create a pipeline when I use `str()` on all the op arguments but I think that causes the op to not interpolate the values and I get a different error at ai platform job runtime.

### Expected result
Creation of custom training job in vertex.

### Materials and Reference

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by cah-parita-desai** [comment]
@Bobgy Were you able to try this one?
I m still stucked at this. 
@ckchow : Were you able to fix this one?

**Comment by SinaChavoshi** [comment]
I believe this issue was fixed by #6473 . Closing as fixed, this is not the case please reopen this bug.

**Comment by cah-parita-desai** [comment]
Hi Sina,

This is not the case.
I am already passing python_module_name as str. 
But still getting the error.

Sample for reference:-

PROJECT_ID = 'xyz'
LOCATION = 'abc'
PIPELINE_ROOT_PATH = 'gs://test'
MODEL_DISPLAY_NAME='custom-test1-template'
PIPELINE_DISPLAY_NAME = 'custom-test-pipeline'
CONTAINER_URI='us-docker.pkg.dev/vertex-ai/training/scikit-learn-cpu.0-23:latest'
STAGING_BUCKET='gs://test1'
BASE_OUTPUT_DIR='gs://test2/custom/'
PYTHON_PACKAGE_GCS_URI='gs://my-bucket/trainer-0.1.tar.gz'
PYTHON_MODULE_NAME='trainer.task'
ENDPOINT_DISPLAY_NAME='custom-pipeline-endpoint'
MODEL_SERVING_CONTAINER_IMAGE_URI='us-docker.pkg.dev/vertex-ai/prediction/sklearn-cpu.0-24:latest'
TRAINING_JOB_NAME='custom-pipeline-job'
REPLICA_COUNT=1
MACHINE_TYPE='n1-standard-4'

def pipeline(
    project: str = PROJECT_ID,
    location: str = LOCATION,
    display_name: str = TRAINING_JOB_NAME,
    python_package_gcs_uri: str = PYTHON_PACKAGE_GCS_URI,
    python_module_name: str = PYTHON_MODULE_NAME,
    container_uri: str = CONTAINER_URI,
    staging_bucket: str = STAGING_BUCKET,
    base_output_dir: str = BASE_OUTPUT_DIR,
    model_serving_container_image_uri: str = MODEL_SERVING_CONTAINER_IMAGE_URI,
    replica_count: int = REPLICA_COUNT,
    machine_type: str =MACHINE_TYPE ,
    model_display_name: str = MODEL_DISPLAY_NAME,
):
       
    training_job_run_op = gcc_aip.CustomPythonPackageTrainingJobRunOp(
            display_name=display_name,
            python_package_gcs_uri=python_package_gcs_uri,
            python_module=python_module_name,
            container_uri=container_uri,
            project=project,
            location=location,
            staging_bucket=staging_bucket,
            base_output_dir=base_output_dir,
            model_serving_container_image_uri=model_serving_container_image_uri,
            replica_count=replica_count,
            machine_type=machine_type,
    )
Note:- I am not able to reopen this issue.

**Comment by Bobgy** [comment]
/assign @SinaChavoshi 
Can you take a look again?

**Comment by cah-parita-desai** [comment]
@SinaChavoshi : Any update on this issue?

**Comment by SinaChavoshi** [comment]
Hi, 

I'm not able to reproduce this error with the sample you provided above. However I noticed in both samples you have parameter named ` python_module=python_module_name,'. This parameter does not exist in the API the correct parameter name is `python_module_name`. see [the API documentation](https://google-cloud-pipeline-components.readthedocs.io/en/gcpc11/google_cloud_pipeline_components.aiplatform.html#google_cloud_pipeline_components.aiplatform.CustomPythonPackageTrainingJobRunOp) for details. 

could you try this and let me know if you are still hitting an issue ?

**Comment by cah-parita-desai** [comment]
Hi Sina,
I did tried with the change as "python_module_name". Below is my function

@kfp.dsl.pipeline(name=PIPELINE_DISPLAY_NAME, pipeline_root=PIPELINE_ROOT_PATH)
def pipeline(
    project: str = PROJECT_ID,
    location: str = LOCATION,
    display_name: str = TRAINING_JOB_NAME,
    python_package_gcs_uri: str = PYTHON_PACKAGE_GCS_URI,
    python_module_name: str = PYTHON_MODULE_NAME,
    container_uri: str = CONTAINER_URI,
    staging_bucket: str = STAGING_BUCKET,
    base_output_dir: str = BASE_OUTPUT_DIR,
    model_serving_container_image_uri: str = MODEL_SERVING_CONTAINER_IMAGE_URI,
    replica_count: int = REPLICA_COUNT,
    machine_type: str =MACHINE_TYPE ,
    model_display_name: str = MODEL_DISPLAY_NAME,
):
    
    training_job_run_op = gcc_aip.CustomPythonPackageTrainingJobRunOp(
            display_name=display_name,
            python_package_gcs_uri=python_package_gcs_uri,
            python_module_name=python_module_name,
            container_uri=container_uri,
            project=project,
            location=location,
            staging_bucket=staging_bucket,
            base_output_dir=base_output_dir,
            model_serving_container_image_uri=model_serving_container_image_uri,
            replica_count=replica_count,
            machine_type=machine_type,
    )
    
         # Upload model
    model_upload_op = gcc_aip.ModelUploadOp(
            project=project,
            display_name=model_display_name,
            artifact_uri=base_output_dir,
            serving_container_image_uri=model_serving_container_image_uri,
        )
    model_upload_op.after(training_job_run_op)

    model_deploy_op = gcc_aip.ModelDeployOp(
            project=project,
            model=model_upload_op.outputs["model"],
            endpoint=aiplatform.Endpoint(
                endpoint_name='personalloan-test2_endpoint').resource_name,
            deployed_model_display_name=model_display_name,
            machine_type="n1-standard-2",
            traffic_percentage=100)

I am passing PYTHON_MODULE_NAME='trainer.task'

Getting below error:-

KeyError                                  Traceback (most recent call last)
<ipython-input-9-57017d2a36e9> in <module>
      2 pip_package_path=PIPELINE_DISPLAY_NAME + ".json"
      3 compiler.Compiler().compile(
----> 4     pipeline_func=pipeline, package_path=pip_package_path
      5 )

/opt/conda/lib/python3.7/site-packages/kfp/v2/compiler/compiler.py in compile(self, pipeline_func, package_path, pipeline_name, pipeline_parameters, type_check)
   1137         pipeline_parameters = {
   1138             param.name: param for param in args_list_with_defaults
-> 1139         }
   1140         # Update pipeline parameters override if there were any.
   1141         pipeline_parameters_override = pipeline_parameters_override or {}

/opt/conda/lib/python3.7/site-packages/kfp/v2/compiler/compiler.py in _create_pipeline_v2(self, pipeline_func, pipeline_name, pipeline_parameters_override)
   1070           pipeline_func: Pipeline function with @dsl.pipeline decorator.
   1071           pipeline_name: The name of the pipeline. Optional.
-> 1072           pipeline_parameters_override: The mapping from parameter names to values.
   1073             Optional.
   1074 

<ipython-input-7-72f66fff9826> in pipeline(project, location, display_name, python_package_gcs_uri, python_module_name, container_uri, staging_bucket, base_output_dir, model_serving_container_image_uri, replica_count, machine_type, model_display_name)
     38             model_serving_container_image_uri=model_serving_container_image_uri,
     39             replica_count=replica_count,
---> 40             machine_type=machine_type,
     41     )
     42 

/opt/conda/lib/python3.7/site-packages/google_cloud_pipeline_components/aiplatform/utils.py in component_yaml_generator(**kwargs)
    531         additional_args = []
    532         for key, args in args_to_serialize.items():
--> 533             for arg_key, value in args.items():
    534                 additional_args.append(f'--{key}.{arg_key}')
    535                 additional_args.append(value)

KeyError: 'python_module_name'

Thanks!

**Comment by SinaChavoshi** [comment]
We are in the process of deprecating this method - see #6474 given that I'm going to close this issue as wont fix. 

The method that we have here is a wrapper around [google.cloud.aiplatform.CustomPythonPackageTrainingJob](https://googleapis.dev/python/aiplatform/latest/aiplatform.html?highlight=custom%20package#google.cloud.aiplatform.CustomPythonPackageTrainingJob) . See [source code here](https://github.com/googleapis/python-aiplatform/blob/8fde2ce4441139784bc0fdd62c88d4b833018765/google/cloud/aiplatform/training_jobs.py#L4650).

Given the error above I suspect you have an older version of `google-cloud-aiplatfrom` that is triggering this issue. 

We are working on a custom_job_wrapper that would allow you to run any component as a custom component. see [custom_training_job_op](https://github.com/SinaChavoshi/pipelines/blob/9326d1d981cf286d71db57a555d8baee35112c48/components/google-cloud/google_cloud_pipeline_components/experimental/custom_job/CustomTrainingJobOp_sample.ipynb)

**Comment by cah-parita-desai** [comment]
Thanks Sina for the update. It helped.
Currently i upgraded the version of google-cloud-aiplatform and tested using CustomPythonPackageTrainingJobRunOp this wrapper.
Can you please provide us production ETA about this new wrapper function which i understand is currently work in progress.

Thank you!
