### ISSUE TITLE
Shared memory issue in Kubeflow when training on GPU cluster

### ISSUE THREAD

**Issue by mikel-brostrom** [kubeflow/pipelines#6510]
### What steps did you take

1. I deployed a pipeline to Kubeflow from my local computer
2. The pipeline starts and
    * The fetch component runs successfully
    * The split component run successfully
    * BUT, the train component gives an error. More specifically:

ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).

### What I tried

1. I ssh:d into my GPU worker pool and increased the smh by:

```bash
sudo mount -o remount,size=8G /dev/shm
```

without any luck.

Any thoughts?

**Comment by zijianjoy** [comment]
Hello @mikel-brostrom , this doesn't seem to be Kubeflow Pipelines related. This is more related to kubernetes because the component runs directly on k8s. Can you try figuring out how much GPU you need on training component and find solution using general k8s approach?

**Comment by mikel-brostrom** [comment]
I fixed it by creating a  pipelinevolme in my dsl.pipeline by:

`smh_vol = kfp.dsl.PipelineVolume(name="shm-vol", empty_dir={"medium": "Memory"})`

and then adding the volume to  my training task by:

`train_task.add_pvolumes({"/dev/shm": smh_vol})`

Could anybody explain why this works??

**Comment by mikel-brostrom** [comment]
But yes @zijianjoy, your are right. This is more Kubernetes related than Kubeflow

**Comment by speaknowpotato** [comment]
hi @mikel-brostrom, I had the same issue. 
I followed your solution to add two lines in my dsl pipeline, 
but it's still not working. 
do you have any idea?
thanks.
