### ISSUE TITLE
upstream connect error or disconnect/reset before headers

### ISSUE THREAD

**Issue by SinaChavoshi** [kubeflow/pipelines#908]
When connecting to KFP or KF UI using the IAP setup. If the system has been idle for a few hours i get the following error 

upstream connect error or disconnect/reset before headers 

Refresh a few times fixes the issue.  I can reproduce this constantly across 3 different clusters.

**Comment by yebrahim** [comment]
That's because IAP [sessions expire](https://cloud.google.com/iap/docs/sessions-howto) in an hour.

This issue can track frontend work to automatically refresh the session automatically, probably by letting the user know it had expired and giving them a button to reload the page.

**Comment by tidylobster** [comment]
I have the same issue except that I don't have to wait for an hour for this to occur. It happens in a few seconds after performing some actions.

**Comment by rileyjbauer** [comment]
Canonical issue for this is here: https://github.com/kubeflow/kubeflow/issues/2852

**Comment by hongye-sun** [comment]
I think the right fix here is to add retries in the kfp client.

**Comment by SinaChavoshi** [comment]
Just validated. The underlying issue is resolved in 0.6.

Cheers,
Sina

**Comment by amygdala** [comment]
Well, I'm still seeing this errorr in 0.6.1... IIRC, this was actually with basic auth.

<img width="466" alt="upstream_connect_error" src="https://user-images.githubusercontent.com/115093/63025119-66f3cb00-be5d-11e9-86b2-96135e0ccc8d.png">

**Comment by SinaChavoshi** [comment]
Nice catch! do you mind updating the
https://github.com/kubeflow/kubeflow/issues/2852 with the details.

**Comment by SinaChavoshi** [comment]
closing this issue as it is tracked /resolved under KF project.
