### ISSUE TITLE
[frontend]: node not marked as failed, state still on running

### ISSUE THREAD

**Issue by axel7083** [kubeflow/pipelines#9603]
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)? manifests

*  KFP version: [2.0.0-rc.1](https://github.com/kubeflow/pipelines/releases/tag/2.0.0-rc.1)

### Steps to reproduce

The `example 2` is the task failed. However it does not appear in the graph. 
![image](https://github.com/kubeflow/pipelines/assets/42176370/6d1fd26b-ca42-4d18-9edd-f5d5b17592cc)

- You can refresh the page, the task will never be shown as failed.
- The state in the tab shows "running".

When checking the `https://{host}/pipeline/apis/v2beta1/runs/{run-id}` we get the information that the task is indeed failed. As shown in the example, here is an extract of the response:

```json
...
"run_details": {
    "task_details": [{
            "run_id": "{run-id}",
            "task_id": "{task-id}",
            "display_name": "example 2",
            "create_time": "...",
            "start_time": "...",
            "end_time": "...",
            "state": "FAILED",
            "state_history": [{
                    "update_time": "2023-06-09T13:41:58Z",
                    "state": "RUNNING"
                }, {
                    "update_time": "2023-06-09T13:42:18Z",
                    "state": "FAILED"
                }
            ],
            "child_tasks": [{
                    "pod_name": "..."
                }
            ]
        },
	...
    ]
}
...
```
---

Impacted by this bug? Give it a 👍.

**Comment by chensun** [comment]
If I recall correctly, we have fixed this issue in the latest version. Can you try 2.0.0?

**Comment by axel7083** [comment]
I migrate to 2.0.0 (`gcr.io/ml-pipeline/frontend:2.0.0`) and the problem still persist.
I made the following steps:
- Migrate from `gcr.io/ml-pipeline/frontend:2.0.0-rc.1` to `gcr.io/ml-pipeline/frontend:2.0.0`
- Cleared my browser cache (to be sure)

The problem appear on pipeline v2

**Comment by axel7083** [comment]
> If I recall correctly, we have fixed this issue in the latest version. Can you try 2.0.0?

After some investigation, I found out, that the meta data execution was not updated. The frontend is not using the https://{host}/pipeline/apis/v2beta1/runs/{run-id} for displaying the current state. It is using execution metadata. And it does not seems to be updated properly. What do you think @chensun
